function C = C_func(in1)
%C_func
%    C = C_func(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Feb-2025 13:44:38

psi1 = in1(:,4);
psi2 = in1(:,5);
psi3 = in1(:,6);
x = in1(:,1);
y = in1(:,2);
z = in1(:,3);
t2 = psi1.^2;
t3 = psi2.^2;
t4 = psi3.^2;
t5 = t2+t3+t4;
t6 = 1.0./t5;
t7 = sqrt(t5);
t8 = 1.0./t7;
t9 = sin(t7);
t10 = t7./2.0;
t11 = sin(t10);
t12 = t11.^2;
C = [x-psi2.*t8.*t9.*3.0-psi1.*psi3.*t6.*t12.*6.0,y+psi1.*t8.*t9.*3.0-psi2.*psi3.*t6.*t12.*6.0,z+t6.*t12.*(t2.*2.0+t3.*2.0).*3.0-3.0];
end
