function C2 = C_zero(in1)
%C_zero
%    C2 = C_zero(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Feb-2025 13:44:39

psi1 = in1(:,4);
psi2 = in1(:,5);
psi3 = in1(:,6);
x = in1(:,1);
y = in1(:,2);
z = in1(:,3);
t2 = psi1.^2;
t3 = psi2.^2;
t4 = psi3.^2;
t5 = t2./6.0;
t6 = t3./6.0;
t7 = t4./6.0;
t8 = t2./4.8e+1;
t9 = t3./4.8e+1;
t10 = t4./4.8e+1;
t11 = t2+t3+t4;
t12 = t11.^2;
t13 = t12./1.2e+2;
t15 = t12./3.84e+3;
t14 = -t13;
t16 = -t15;
t17 = t5+t6+t7+t14-1.0;
t18 = t8+t9+t10+t16-1.0./2.0;
C2 = [x+psi2.*t17.*3.0+psi1.*psi3.*t18.*6.0,y-psi1.*t17.*3.0+psi2.*psi3.*t18.*6.0,z-t18.*(t2.*2.0+t3.*2.0).*3.0-3.0];
end
