function Cq = Cq_func(in1)
%Cq_func
%    Cq = Cq_func(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Feb-2025 16:00:45

psi1 = in1(:,4);
psi2 = in1(:,5);
psi3 = in1(:,6);
t2 = psi1.^2;
t3 = psi2.^2;
t4 = psi3.^2;
t5 = t2+t3+t4;
t6 = 1.0./t5;
t8 = sqrt(t5);
t7 = t6.^2;
t9 = t8.^3;
t11 = cos(t8);
t12 = sin(t8);
t13 = t8./2.0;
t10 = 1.0./t9;
t14 = t11-1.0;
t15 = sin(t13);
t16 = cos(t13);
t17 = t11./2.0;
t21 = t9.*t12.*3.0;
t22 = psi1.*psi2.*t6.*t11.*3.0;
t24 = psi1.*psi2.*psi3.*t8.*t12.*3.0;
t18 = psi1.*psi2.*psi3.*t14.*6.0;
t19 = t4.*t15.*2.0;
t20 = t17-1.0./2.0;
t23 = psi1.*psi2.*t10.*t12.*3.0;
t25 = psi3.*t6.*t14.*3.0;
t26 = t2.*t8.*t16;
t27 = t3.*t8.*t16;
t28 = t19+t26+t27;
Cq = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-t22+t23+t25-psi3.*t2.*t10.*t12.*3.0-psi3.*t2.*t7.*t20.*1.2e+1,-t7.*(t18-t21+t24-t2.*t5.*t11.*3.0+t2.*t8.*t12.*3.0),psi1.*t7.*t15.*t28.*6.0,-t7.*(t18+t21+t24+t3.*t5.*t11.*3.0-t3.*t8.*t12.*3.0),t22-t23+t25-psi3.*t3.*t10.*t12.*3.0-psi3.*t3.*t7.*t20.*1.2e+1,psi2.*t7.*t15.*t28.*6.0,psi1.*t6.*t14.*3.0-psi2.*psi3.*t6.*t11.*3.0+psi2.*psi3.*t10.*t12.*3.0-psi1.*t4.*t10.*t12.*3.0-psi1.*t4.*t7.*t20.*1.2e+1,psi2.*t6.*t14.*3.0+psi1.*psi3.*t6.*t11.*3.0-psi1.*psi3.*t10.*t12.*3.0-psi2.*t4.*t10.*t12.*3.0-psi2.*t4.*t7.*t20.*1.2e+1,psi3.*t7.*t15.*(t2+t3).*(t15.*2.0-t8.*t16).*-6.0],[3,6]);
end
