function Cq_qd = Cq_qd_func(in1,in2)
%Cq_qd_func
%    Cq_qd = Cq_qd_func(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Feb-2025 13:44:41

psi1 = in1(:,4);
psi2 = in1(:,5);
psi3 = in1(:,6);
psi1d = in2(:,4);
psi2d = in2(:,5);
psi3d = in2(:,6);
xd = in2(:,1);
yd = in2(:,2);
zd = in2(:,3);
t2 = psi1.^2;
t3 = psi2.^2;
t4 = psi3.^2;
t5 = t2.*2.0;
t6 = t3.*2.0;
t7 = t2+t3+t4;
t8 = t5+t6;
t9 = 1.0./t7;
t11 = sqrt(t7);
t10 = t9.^2;
t12 = 1.0./t11;
t14 = cos(t11);
t15 = sin(t11);
t16 = t11./2.0;
t13 = t12.^3;
t17 = sin(t16);
t18 = cos(t16);
t20 = psi1.*psi2.*t9.*t14.*3.0;
t21 = t12.*t15.*3.0;
t19 = t17.^2;
t22 = psi1.*psi2.*t13.*t15.*3.0;
t25 = psi1.*psi2.*psi3.*t13.*t17.*t18.*6.0;
t23 = psi3.*t9.*t19.*6.0;
t24 = psi1.*psi2.*psi3.*t10.*t19.*1.2e+1;
mt1 = [xd-psi3d.*(psi1.*t9.*t19.*6.0+psi2.*psi3.*t9.*t14.*3.0-psi2.*psi3.*t13.*t15.*3.0-psi1.*t4.*t10.*t19.*1.2e+1+psi1.*t4.*t13.*t17.*t18.*6.0)-psi2d.*(t21-t24+t25+t3.*t9.*t14.*3.0-t3.*t13.*t15.*3.0)-psi1d.*(t20-t22+t23-psi3.*t2.*t10.*t19.*1.2e+1+psi3.*t2.*t13.*t17.*t18.*6.0);yd-psi3d.*(psi2.*t9.*t19.*6.0-psi1.*psi3.*t9.*t14.*3.0+psi1.*psi3.*t13.*t15.*3.0-psi2.*t4.*t10.*t19.*1.2e+1+psi2.*t4.*t13.*t17.*t18.*6.0)+psi1d.*(t21+t24-t25+t2.*t9.*t14.*3.0-t2.*t13.*t15.*3.0)-psi2d.*(-t20+t22+t23-psi3.*t3.*t10.*t19.*1.2e+1+psi3.*t3.*t13.*t17.*t18.*6.0)];
mt2 = [zd+psi1d.*(psi1.*t9.*t19.*1.2e+1-psi1.*t8.*t10.*t19.*6.0+psi1.*t8.*t13.*t17.*t18.*3.0)+psi2d.*(psi2.*t9.*t19.*1.2e+1-psi2.*t8.*t10.*t19.*6.0+psi2.*t8.*t13.*t17.*t18.*3.0)-psi3d.*(psi3.*t8.*t10.*t19.*6.0-psi3.*t8.*t13.*t17.*t18.*3.0)];
Cq_qd = [mt1;mt2];
end
