function Cq2_qd = Cq_qd_zero(in1,in2)
%Cq_qd_zero
%    Cq2_qd = Cq_qd_zero(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Feb-2025 13:44:42

psi1 = in1(:,4);
psi2 = in1(:,5);
psi3 = in1(:,6);
psi1d = in2(:,4);
psi2d = in2(:,5);
psi3d = in2(:,6);
xd = in2(:,1);
yd = in2(:,2);
zd = in2(:,3);
t2 = psi1.^2;
t3 = psi2.^2;
t4 = psi3.^2;
t7 = psi1./3.0;
t8 = psi2./3.0;
t9 = psi3./3.0;
t10 = psi1./2.4e+1;
t11 = psi2./2.4e+1;
t12 = psi3./2.4e+1;
t5 = t2.*2.0;
t6 = t3.*2.0;
t13 = t2./2.0;
t14 = t3./2.0;
t15 = t4./2.0;
t16 = t2./4.8e+1;
t17 = t3./4.8e+1;
t18 = t4./4.8e+1;
t19 = t2+t3+t4;
t20 = t5+t6;
t21 = t19.^2;
t22 = (psi1.*t19)./3.0e+1;
t23 = (psi2.*t19)./3.0e+1;
t24 = (psi3.*t19)./3.0e+1;
t30 = (psi1.*t19)./9.6e+2;
t31 = (psi2.*t19)./9.6e+2;
t32 = (psi3.*t19)./9.6e+2;
t25 = t21./4.0e+1;
t26 = -t22;
t27 = -t23;
t28 = -t24;
t33 = t21./3.84e+3;
t34 = -t30;
t35 = -t31;
t36 = -t32;
t29 = -t25;
t37 = -t33;
t38 = t7+t26;
t39 = t8+t27;
t40 = t9+t28;
t41 = t10+t34;
t42 = t11+t35;
t43 = t12+t36;
t44 = t16+t17+t18+t37-1.0./2.0;
t45 = psi3.*t44.*6.0;
Cq2_qd = [xd+psi3d.*(psi2.*t40.*3.0+psi1.*t44.*6.0+psi1.*psi3.*t43.*6.0)+psi1d.*(t45+psi2.*t38.*3.0+psi1.*psi3.*t41.*6.0)+psi2d.*(t13+t14+t15+t29+psi2.*t39.*3.0+psi1.*psi3.*t42.*6.0-3.0);yd+psi3d.*(psi1.*t40.*-3.0+psi2.*t44.*6.0+psi2.*psi3.*t43.*6.0)+psi2d.*(t45-psi1.*t39.*3.0+psi2.*psi3.*t42.*6.0)-psi1d.*(t13+t14+t15+t29+psi1.*t38.*3.0-psi2.*psi3.*t41.*6.0-3.0);zd-psi1d.*(psi1.*t44.*1.2e+1+t20.*t41.*3.0)-psi2d.*(psi2.*t44.*1.2e+1+t20.*t42.*3.0)-psi3d.*t20.*t43.*3.0];
end
