function Cq2 = Cq_zero(in1)
%Cq_zero
%    Cq2 = Cq_zero(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Feb-2025 16:00:46

psi1 = in1(:,4);
psi2 = in1(:,5);
psi3 = in1(:,6);
t2 = psi1.^2;
t3 = psi2.^2;
t4 = psi3.^2;
t7 = psi1./2.4e+1;
t8 = psi2./2.4e+1;
t5 = t2.*2.0;
t6 = t3.*2.0;
t9 = t2./2.0;
t10 = t3./2.0;
t11 = t4./2.0;
t12 = t2./4.8e+1;
t13 = t3./4.8e+1;
t14 = t4./4.8e+1;
t15 = t2+t3+t4;
t16 = t5+t6;
t17 = t15.^2;
t18 = t15-1.0e+1;
t21 = (psi1.*t15)./9.6e+2;
t22 = (psi2.*t15)./9.6e+2;
t19 = t18-3.0e+1;
t20 = t17./4.0e+1;
t23 = t17./3.84e+3;
t24 = -t21;
t25 = -t22;
t26 = (psi1.*psi2.*t18)./1.0e+1;
t27 = -t23;
t28 = t7+t24;
t29 = t8+t25;
t30 = t12+t13+t14+t27-1.0./2.0;
t31 = psi3.*t30.*6.0;
Cq2 = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-t26+t31-(psi3.*t2.*t19)./1.6e+2,-t9-t10-t11+t20-psi1.*(psi1./3.0-(psi1.*t15)./3.0e+1).*3.0+psi2.*psi3.*t28.*6.0+3.0,psi1.*t30.*-1.2e+1-t16.*t28.*3.0,t9+t10+t11-t20+psi2.*(psi2./3.0-(psi2.*t15)./3.0e+1).*3.0+psi1.*psi3.*t29.*6.0-3.0,t26+t31-(psi3.*t3.*t19)./1.6e+2,psi2.*t30.*-1.2e+1-t16.*t29.*3.0,psi1.*t30.*6.0-(psi2.*psi3.*t18)./1.0e+1-(psi1.*t4.*t19)./1.6e+2,psi2.*t30.*6.0+(psi1.*psi3.*t18)./1.0e+1-(psi2.*t4.*t19)./1.6e+2,(psi3.*t16.*t19)./3.2e+2],[3,6]);
end
