function Qc_sym2 = Qc_zero(in1,in2)
%Qc_zero
%    Qc_sym2 = Qc_zero(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Feb-2025 16:00:46

psi1 = in1(:,4);
psi2 = in1(:,5);
psi3 = in1(:,6);
psi1d = in2(:,4);
psi2d = in2(:,5);
psi3d = in2(:,6);
t2 = psi1.^2;
t3 = psi1.^3;
t4 = psi2.^2;
t6 = psi2.^3;
t7 = psi3.^2;
t9 = psi3.^3;
t11 = psi1d.^2;
t12 = psi2d.^2;
t13 = psi3d.^2;
t5 = t2.^2;
t8 = t4.^2;
t10 = t7.^2;
et1 = psi1d.*psi3d.*6.0-psi2.*t11-psi2.*t12.*3.0-psi2.*t13+(t6.*t11)./1.0e+1+(t6.*t12)./2.0+(t6.*t13)./1.0e+1-psi1.*psi1d.*psi2d.*2.0-psi3.*psi2d.*psi3d.*2.0-psi1.*psi3.*t11.*(3.0./4.0)-(psi1.*psi3.*t12)./4.0-psi1.*psi3.*t13.*(3.0./4.0)+(psi1d.*psi2d.*t3)./5.0-psi1d.*psi3d.*t2.*(3.0./4.0)-(psi1d.*psi3d.*t4)./4.0+(psi1d.*psi3d.*t5)./6.4e+1-psi1d.*psi3d.*t7.*(3.0./4.0)+(psi1d.*psi3d.*t8)./3.2e+2+(psi1d.*psi3d.*t10)./6.4e+1+(psi2d.*psi3d.*t9)./5.0+psi2.*t2.*t11.*(3.0./1.0e+1)+psi2.*t2.*t12.*(3.0./1.0e+1)+(psi2.*t2.*t13)./1.0e+1+(psi3.*t3.*t11)./3.2e+1+(psi3.*t3.*t12)./1.6e+2+psi3.*t3.*t13.*(3.0./1.6e+2)+(psi2.*t7.*t11)./1.0e+1;
et2 = psi1.*t9.*t11.*(3.0./1.6e+2)+psi2.*t7.*t12.*(3.0./1.0e+1)+(psi1.*t9.*t12)./1.6e+2+psi2.*t7.*t13.*(3.0./1.0e+1)+(psi1.*t9.*t13)./3.2e+1-(psi1.*psi2.*psi2d.*psi3d)./2.0-(psi2.*psi3.*psi1d.*psi2d)./2.0+psi1.*psi1d.*psi2d.*t4.*(3.0./5.0)+(psi2.*psi2d.*psi3d.*t3)./8.0e+1+(psi3.*psi2d.*psi3d.*t2)./5.0+(psi1.*psi1d.*psi2d.*t7)./5.0+(psi1.*psi2d.*psi3d.*t6)./8.0e+1+(psi3.*psi1d.*psi2d.*t6)./8.0e+1+psi3.*psi2d.*psi3d.*t4.*(3.0./5.0)+(psi2.*psi1d.*psi2d.*t9)./8.0e+1+psi1.*psi3.*t4.*t11.*(3.0./1.6e+2)+psi1.*psi3.*t4.*t12.*(3.0./1.6e+2)+psi1.*psi3.*t4.*t13.*(3.0./1.6e+2)+psi1d.*psi3d.*t2.*t4.*(3.0./1.6e+2)+psi1d.*psi3d.*t2.*t7.*(9.0./1.6e+2)+psi1d.*psi3d.*t4.*t7.*(3.0./1.6e+2);
et3 = psi1.*psi2.*psi3.*psi1d.*psi3d.*(2.0./5.0)+psi2.*psi3.*psi1d.*psi2d.*t2.*(3.0./8.0e+1)+psi1.*psi2.*psi2d.*psi3d.*t7.*(3.0./8.0e+1);
et4 = psi2d.*psi3d.*6.0+psi1.*t11.*3.0+psi1.*t12+psi1.*t13-(t3.*t11)./2.0-(t3.*t12)./1.0e+1-(t3.*t13)./1.0e+1+psi2.*psi1d.*psi2d.*2.0+psi3.*psi1d.*psi3d.*2.0-(psi2.*psi3.*t11)./4.0-psi2.*psi3.*t12.*(3.0./4.0)-psi2.*psi3.*t13.*(3.0./4.0)-(psi2d.*psi3d.*t2)./4.0-(psi1d.*psi2d.*t6)./5.0-psi2d.*psi3d.*t4.*(3.0./4.0)+(psi2d.*psi3d.*t5)./3.2e+2-psi2d.*psi3d.*t7.*(3.0./4.0)-(psi1d.*psi3d.*t9)./5.0+(psi2d.*psi3d.*t8)./6.4e+1+(psi2d.*psi3d.*t10)./6.4e+1-psi1.*t4.*t11.*(3.0./1.0e+1)-psi1.*t4.*t12.*(3.0./1.0e+1)-(psi1.*t4.*t13)./1.0e+1-psi1.*t7.*t11.*(3.0./1.0e+1)-(psi1.*t7.*t12)./1.0e+1+(psi3.*t6.*t11)./1.6e+2;
et5 = psi1.*t7.*t13.*(-3.0./1.0e+1)+(psi3.*t6.*t12)./3.2e+1+(psi2.*t9.*t11)./1.6e+2+psi3.*t6.*t13.*(3.0./1.6e+2)+psi2.*t9.*t12.*(3.0./1.6e+2)+(psi2.*t9.*t13)./3.2e+1-(psi1.*psi2.*psi1d.*psi3d)./2.0-(psi1.*psi3.*psi1d.*psi2d)./2.0-psi2.*psi1d.*psi2d.*t2.*(3.0./5.0)+(psi2.*psi1d.*psi3d.*t3)./8.0e+1+(psi3.*psi1d.*psi2d.*t3)./8.0e+1-psi3.*psi1d.*psi3d.*t2.*(3.0./5.0)+(psi1.*psi1d.*psi3d.*t6)./8.0e+1-(psi3.*psi1d.*psi3d.*t4)./5.0-(psi2.*psi1d.*psi2d.*t7)./5.0+(psi1.*psi1d.*psi2d.*t9)./8.0e+1+psi2.*psi3.*t2.*t11.*(3.0./1.6e+2)+psi2.*psi3.*t2.*t12.*(3.0./1.6e+2)+psi2.*psi3.*t2.*t13.*(3.0./1.6e+2)+psi2d.*psi3d.*t2.*t4.*(3.0./1.6e+2)+psi2d.*psi3d.*t2.*t7.*(3.0./1.6e+2);
et6 = psi2d.*psi3d.*t4.*t7.*(9.0./1.6e+2)-psi1.*psi2.*psi3.*psi2d.*psi3d.*(2.0./5.0)+psi1.*psi3.*psi1d.*psi2d.*t4.*(3.0./8.0e+1)+psi1.*psi2.*psi1d.*psi3d.*t7.*(3.0./8.0e+1);
et7 = t11.*-6.0-t12.*6.0+t2.*t11.*(3.0./2.0)+(t2.*t12)./2.0+(t2.*t13)./4.0+(t4.*t11)./2.0+t4.*t12.*(3.0./2.0)-t5.*t11.*(3.0./6.4e+1)+(t4.*t13)./4.0-t5.*t12.*(3.0./3.2e+2)-(t5.*t13)./1.6e+2+(t7.*t11)./4.0+(t7.*t12)./4.0-t8.*t11.*(3.0./3.2e+2)-t8.*t12.*(3.0./6.4e+1)-(t8.*t13)./1.6e+2-(t10.*t11)./3.2e+2-(t10.*t12)./3.2e+2-t2.*t4.*t11.*(9.0./1.6e+2)-t2.*t4.*t12.*(9.0./1.6e+2)-(t2.*t4.*t13)./8.0e+1-t2.*t7.*t11.*(3.0./8.0e+1)-(t2.*t7.*t12)./8.0e+1-t2.*t7.*t13.*(3.0./1.6e+2)-(t4.*t7.*t11)./8.0e+1;
et8 = t4.*t7.*t12.*(-3.0./8.0e+1)-t4.*t7.*t13.*(3.0./1.6e+2)+psi1.*psi2.*psi1d.*psi2d.*2.0+psi1.*psi3.*psi1d.*psi3d+psi2.*psi3.*psi2d.*psi3d-psi2.*psi1d.*psi2d.*t3.*(3.0./4.0e+1)-psi1.*psi1d.*psi2d.*t6.*(3.0./4.0e+1)-(psi3.*psi1d.*psi3d.*t3)./2.0e+1-(psi1.*psi1d.*psi3d.*t9)./4.0e+1-(psi3.*psi2d.*psi3d.*t6)./2.0e+1-(psi2.*psi2d.*psi3d.*t9)./4.0e+1-(psi1.*psi3.*psi1d.*psi3d.*t4)./2.0e+1-(psi2.*psi3.*psi2d.*psi3d.*t2)./2.0e+1-(psi1.*psi2.*psi1d.*psi2d.*t7)./2.0e+1;
Qc_sym2 = [et1+et2+et3;et4+et5+et6;et7+et8];
end
